### ISSUE TITLE
Logon error: bnet: Received unexpected packet

### ISSUE THREAD

**Issue by AncientiCe** [nielsAD/gowarcraft3#12]
Hi,

Any idea why i get this when trying a pvpgn server?
Trace to here bnet.go@sendLogonProof

**Comment by nielsAD** [comment]
Can you provide some more information?
What are you trying to run? What version? What server? What's the full error?

**Comment by AncientiCe** [comment]
Correction: After some account changes i figured out the problem is being in a clan. Tested it with a fresh account.
To repro:
Login -> join clan -> try to login again via bncsclient -> 10:06:44 Logon error: bnet: Received unexpected packet

**Comment by AncientiCe** [comment]
There's an UnknownPacket right before AuthAccountLogonProofResp which causes the program to exit in the method I mentioned.
Skipping the packet and waiting for AuthAccountLogonProofResp seems to fix the problem.
```
for {
		pkt, err := conn.NextPacket(10 * time.Second)
		if err != nil {
			return nil, err
		}
		switch p := pkt.(type) {
		case *bncs.AuthAccountLogonProofResp:
			return p, nil
		}
	}
```

**Comment by nielsAD** [comment]
Thanks. As not all private servers strictly follow protocol, bfda02e6ef6481fd41f4009f730ac7b7723d5883 adds more leniency to the bncs handshake.
