### ISSUE TITLE
Request: add support for fakeplayers to join desired pvpgn games

### ISSUE THREAD

**Issue by padinitz** [nielsAD/gowarcraft3#5]
I'm making wc3 maps for old 1.26-1.28 clients and most of my players are located on rubattle.net, europebattle.net and other community platforms.

For testing i need to somehow add fakeplayers to pvpgn games located by name/ip address.

Can you add support for pvpgn fakeplayer join? I can pay if you want to.

Thanks.

**Comment by nielsAD** [comment]
Joining external lobbies works fine when you have the host (IP and port) and game ID. You can find out the game ID by snooping the network (using `w3gsdump` for example) or by sending a [`GetAdvListReq`](https://godoc.org/github.com/nielsAD/gowarcraft3/protocol/bncs#GetAdvListReq) packet to the bnet server if you want to automate things.

I want to keep the tools rather minimal for now, so I'm not going to add this as a separate feature. However, you might be able to glue some things together to implement this yourself without too much hassle.
