### ISSUE TITLE
[Question] Sending commands to opened battle.net server

### ISSUE THREAD

**Issue by webkitten** [nielsAD/gowarcraft3#6]
Hi there! 

Is there some way to send commands to opened warcraft tft game / channel / lobby?

I need to create game (/host 5x5 ap qwewqe), control slots (/open 2 5), starting games (/start)

**Comment by nielsAD** [comment]
The code for interacting with Battle.net is based on the old protocol (up until game version 1.30.1). It will not work for the current retail version. I guess I'll add a disclaimer in the readme for that.

If you are targeting older versions of the game, then yes it's possible, just take a look at the `bncsclient` and `w3gsclient` programs for examples.
