### ISSUE TITLE
w3gsdump stopped working

### ISSUE THREAD

**Issue by webkitten** [nielsAD/gowarcraft3#7]
Hi! I used your w3gsdump.exe script with parsing output data in my node.js app and it was awesome (i could recognize what slot uses player and it's nickname in lobby by checking "PlayerInfo" and "SlotInfo")

But some time ago it changed: "SlotInfo" works only once, when i'm entering lobby and script doesn't respond other events

Warcraft 3 version: 1.26.0.6401
Battle.net platform: iccup

**Comment by nielsAD** [comment]
Can you elaborate a bit on what changed? Did it stop working when you upgraded to a new version?

**Comment by webkitten** [comment]
version of wc3 didn't change
i'll try check on some other platforms

**Comment by webkitten** [comment]
![w3gsdump](https://github.com/webkitten/webkitten.github.io/raw/master/img/w3gsdump.png)

**Comment by nielsAD** [comment]
If the Wireshark plugin is also showing unknown packets, it's likely that iccup has changed something. If you can attach a Wireshark dump, maybe I can look into it, but for now I cannot reproduce this.
