### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by AncientiCe** [nielsAD/gowarcraft3#8]
Hi,

I'm trying to build the project but it fails on both test and release:
```
gowarcraft3/vendor/StormLib/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:58:12: error: implicit declaration of function 'LibTomMalloc' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  tmpbuf = XMALLOC(siglen);
  ```

Any ideas on this?
MacOS Big Sur / 11.2.1

**Comment by nielsAD** [comment]
I have not seen this before, but it seems related to [StormLib](https://github.com/ladislav-zezula/StormLib), a third party library. Can you try building this manually? I don't have access to a macOS system, but build/tests do seem to pass on macOS via Travis.

Maybe we have to update StormLib to a newer version, but I don't see anything in their changelog related to this.

**Comment by AncientiCe** [comment]
Tried building only the module and I got the same message.
Will do some tries, see if i can fix it, maybe it's a dependency I don't have.
I think we can close this since you can't repro it on Travis and i'll come back if i find something.

Off: I think a package changed url
https://github.com/nielsAD/gowarcraft3/compare/master...AncientiCe:master

**Comment by AncientiCe** [comment]
Adding the defined functions in the StormLib package fixed it for me.
Closing (hopefully i'll have time to create a PR on the package repo)
